### ISSUE TITLE
unable to access Picker Object to customize it more.

### ISSUE THREAD

**Issue by sameer4** [hackiftekhar/IQDropDownTextField#65]
i wanted to set minuteInterval in IQDropDownModeTimePicker but there's no option like this nor i can access picker object to customize it in my own code.i had to edit h and m files directly.but this can cause problem if other developer updated the files without noticing the changes.can you update the code?

**Comment by hackiftekhar** [comment]
@sameer4 Changes done. Cheers!

**Comment by gask** [comment]
@hackiftekhar I'm trying to set the minuteInterval of the datePicker object inside a IQDropDownTextField object with IQDropDownModeTimePicker and nothing is changing. Are there other ways of setting the minuteInterval of the datePicker instead of "field.datePicker.minuteInterval"?

Because if there is not, this is a bug.
